import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { formatDate } from "@/lib/utils";
import { FileText, ArrowUpRight, Clock } from "lucide-react";
import GenerateReportButton from "@/components/features/admin/generate-report-button";

export const dynamic = "force-dynamic";

interface ReportsPageProps {
  params: Promise<{ id: string }>;
}

const statusStyles: Record<string, { dot: string; label: string }> = {
  COMPLETED: { dot: "#22c55e", label: "Completed" },
  GENERATING: { dot: "#f59e0b", label: "Generating" },
  FAILED: { dot: "#ef4444", label: "Failed" },
  DRAFT: { dot: "#6B7280", label: "Draft" },
};

export default async function AdminClientReportsPage({ params }: ReportsPageProps) {
  const { id } = await params;
  const client = await prisma.client.findUnique({
    where: { id },
    select: { brandName: true },
  });

  if (!client) notFound();

  const reports = await prisma.report.findMany({
    where: { clientId: id },
    include: {
      generator: { select: { username: true } },
      sections: { orderBy: { sortOrder: "asc" } },
    },
    orderBy: [{ year: "desc" }, { month: "desc" }],
  });

  return (
    <div className="px-8 py-8 max-w-[1440px] mx-auto w-full space-y-6">
      {/* Generate CTA */}
      <div className="bg-white border border-[#ECECF4] rounded-[24px] p-7 flex items-center justify-between">
        <div>
          <h2 className="text-lg font-bold text-[#111827]">Monthly Reports</h2>
          <p className="text-[15px] text-[#6B7280] mt-1">
            Generate and review performance reports for {client.brandName}.
          </p>
        </div>
        <GenerateReportButton clientId={id} />
      </div>

      {/* Report History */}
      <div className="bg-white border border-[#ECECF4] rounded-[24px] p-7">
        <h3 className="text-lg font-bold text-[#111827] mb-1">Report History</h3>
        <p className="text-[15px] text-[#6B7280] mb-6">Past monthly performance reports</p>

        {reports.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-12 text-center">
            <Clock className="w-12 h-12 text-[#D1D5DB] mb-3" />
            <p className="text-[15px] font-medium text-[#6B7280]">No monthly reports have been generated yet.</p>
            <p className="text-xs text-[#9CA3AF] mt-1">Generate your first report to start tracking performance over time.</p>
          </div>
        ) : (
          <div className="space-y-3">
            {reports.map((report) => {
              const monthLabel = new Date(report.year, report.month - 1).toLocaleString("en-US", {
                month: "long",
                year: "numeric",
              });
              const status = statusStyles[report.status] || statusStyles.DRAFT;

              return (
                <div
                  key={report.id}
                  className="flex items-center justify-between py-4 px-5 rounded-xl border border-[#ECECF4] hover:border-gray-200 transition-colors"
                >
                  <div className="flex items-center gap-4 min-w-0">
                    <div className="w-10 h-10 rounded-xl bg-[#F6F7FB] flex items-center justify-center shrink-0">
                      <FileText className="w-5 h-5 text-[#6B7280]" />
                    </div>
                    <div className="min-w-0">
                      <p className="text-[15px] font-semibold text-[#111827]">{monthLabel} Report</p>
                      <p className="text-xs text-[#9CA3AF] mt-0.5">
                        {report.sections.length} section{report.sections.length !== 1 ? "s" : ""} · Generated by {report.generator?.username ?? "system"}
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center gap-5 shrink-0">
                    <span className="flex items-center gap-1.5 text-xs font-semibold" style={{ color: status.dot }}>
                      <span className="w-1.5 h-1.5 rounded-full shrink-0" style={{ backgroundColor: status.dot }} />
                      {status.label}
                    </span>
                    <span className="text-xs text-[#9CA3AF]">{formatDate(report.createdAt, "MMM d, yyyy")}</span>
                    <ArrowUpRight className="w-3.5 h-3.5 text-[#9CA3AF]" />
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
