import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import StatusBadge from "@/components/shared/status-badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export const dynamic = "force-dynamic";

interface ReportsPageProps {
  params: Promise<{ id: string }>;
}

export default async function AdminClientReportsPage({ params }: ReportsPageProps) {
  const { id } = await params;
  const client = await prisma.client.findUnique({
    where: { id },
    select: { brandName: true },
  });

  if (!client) notFound();

  const reports = await prisma.report.findMany({
    where: { clientId: id },
    include: {
      generator: { select: { username: true } },
      sections: { orderBy: { sortOrder: "asc" } },
    },
    orderBy: [{ year: "desc" }, { month: "desc" }],
  });

  return (
    <div className="space-y-6">
      <header>
        <h1 className="text-xl font-bold tracking-tight text-foreground">Reports</h1>
        <p className="text-sm text-muted-foreground">
          Monthly performance reports generated for {client.brandName}.
        </p>
      </header>

      <Card className="border-border bg-card">
        <CardHeader>
          <CardTitle className="text-base">Report History</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          {reports.length === 0 ? (
            <p className="text-sm text-muted-foreground">No monthly reports have been generated yet.</p>
          ) : (
            reports.map((report) => (
              <div key={report.id} className="grid grid-cols-1 md:grid-cols-[1fr_auto_auto] items-center gap-3 rounded-md border border-border/60 p-3">
                <div>
                  <p className="text-sm font-medium text-foreground">
                    {new Date(report.year, report.month - 1).toLocaleString("en-US", {
                      month: "long",
                      year: "numeric",
                    })}
                  </p>
                  <p className="text-xs text-muted-foreground">
                    {report.sections.length} sections · Generated by {report.generator?.username ?? "system"}
                  </p>
                </div>
                <StatusBadge status={report.status} />
                <p className="text-xs text-muted-foreground">{report.createdAt.toLocaleDateString()}</p>
              </div>
            ))
          )}
        </CardContent>
      </Card>
    </div>
  );
}
